import type { Song } from '@/types'

export const songs: Song[] = [
  {
    id: 1,
    artist: 'TVARI',
    title: 'Tokyo Cafe',
    source: '/songs/song1.mp3',
    cover: '/covers/song1.webp',
    favorite: false,
  },
  {
    id: 2,
    artist: 'Top-Flow',
    title: 'Summer Party',
    source: '/songs/song2.mp3',
    cover: '/covers/song2.webp',
    favorite: false,
  },
  {
    id: 3,
    artist: 'TVARI',
    title: 'Venice Beach',
    source: '/songs/song3.mp3',
    cover: '/covers/song3.webp',
    favorite: false,
  },
  {
    id: 4,
    artist: 'Denys Brodovskyi',
    title: 'Ethereal Vistas',
    source: '/songs/song4.mp3',
    cover: '/covers/song4.webp',
    favorite: false,
  },
  {
    id: 5,
    artist: 'Pumpupthemind',
    title: 'Once In Paris',
    source: '/songs/song5.mp3',
    cover: '/covers/song5.webp',
    favorite: false,
  },
  {
    id: 6,
    artist: 'Luca Francini',
    title: 'Solitude',
    source: '/songs/song6.mp3',
    cover: '/covers/song6.webp',
    favorite: false,
  },
  {
    id: 7,
    artist: 'prazkhanal',
    title: 'Whip',
    source: '/songs/song7.mp3',
    cover: '/covers/song7.webp',
    favorite: false,
  },
]
